In [1]:
3 + 5

8

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones_like(np.arange(1,7).reshape(2,3))

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [18]:
x = np.arange(1,11).reshape(2,5)
x.dtype

dtype('int32')

In [17]:
(np.ones_like(x)).dtype

dtype('int32')

In [22]:
np.full((3,5),7, dtype=float)

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [31]:
np.full_like(np.array([[1,2,3],[4,5,6]]),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [33]:
np.full((2, 2), "Hamdi")

array([['Hamdi', 'Hamdi'],
       ['Hamdi', 'Hamdi']], dtype='<U5')

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [41]:
np.random.rand(3)

array([0.54825096, 0.39072574, 0.76642729])

In [42]:
np.random.randn(2, 2)

array([[ 1.55399906, -0.99251631],
       [ 1.1398328 ,  0.47919989]])

In [113]:
np.random.randint(2, 5, size=3)

array([2, 4, 3])

In [153]:
np.random.rand(2)

array([0.20289707, 0.61832041])

In [150]:
np.random.randn()

-0.8760584608748223

In [156]:
np.argmax(np.array([[1, 3], [4, 2]]))

2

In [157]:
y = np.arange(0,10).reshape(2,-1)

In [163]:
y.size

10

In [166]:
np.transpose(y)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [167]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [162]:
np.min(y,axis=0)

array([0, 1, 2, 3, 4])

In [165]:
( np.array([1, 2, 3], dtype=np.int32)).itemsize

4

In [169]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [184]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [179]:
a = np.array([[1], [2], [3]])

b = np.array([[4], [5], [6]])

np.concatenate((a, b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [187]:
a = np.array([[1], [2], [3]])

b = np.array([[4], [5], [6]])

np.hstack([a, b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [188]:
a = np.array([[1], [2], [3]])

b = np.array([[4], [5], [6]])

np.vstack([a, b])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [189]:
np.split(np.array([1, 2, 3, 4]), 2)

[array([1, 2]), array([3, 4])]

In [191]:
np.array_split(np.array([1, 2, 3, 4, 5]), 2)

[array([1, 2, 3]), array([4, 5])]

In [192]:
np.hsplit(np.array([[1, 2], [3, 4]]), 2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [193]:
np.array_split(np.array([1, 2, 3, 4, 5, 6]), 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [194]:
a = np.array([[1], [2], [3]])

b = np.array([[4], [5], [6]])

np.hstack([a, b])

array([[1, 4],
       [2, 5],
       [3, 6]])