https://www.stratascratch.com/

## Numpy soruları

### 1. Numpy nedir ne amaçla kullanılır?

https://numpy.org/doc/stable/user/absolute_beginners.html#

NumPy (Sayısal Python), bilim ve mühendislikte yaygın olarak kullanılan açık kaynaklı bir Python kütüphanesidir. NumPy kütüphanesi, homojen, N boyutlu ndarray gibi çok boyutlu dizi veri yapıları ve bu veri yapıları üzerinde etkili bir şekilde çalışan büyük bir fonksiyon kütüphanesi içerir.

NumPy, aşağıdakiler dahil olmak üzere geniş bir uygulama yelpazesi için kullanılır:

Bilimsel Hesaplama: NumPy, matematiksel, bilimsel ve mühendislik hesaplamaları için olmazsa olmaz bir araçtır. Verimli dizi işlemleri, doğrusal cebir rutinleri, Fourier dönüşümleri ve rastgele sayı üretimi gibi özellikler sunar.

Veri Analizi: NumPy, büyük veri kümelerini işlemede ve analiz etmede oldukça etkilidir. Verileri temizleme, dönüştürme ve şekillendirme gibi görevleri kolaylaştırır.

Makine Öğrenmesi: NumPy dizileri, çoğu makine öğrenmesi algoritması için verimli bir veri yapısı sağlar. Scikit-learn gibi birçok makine öğrenmesi kütüphanesi, NumPy dizilerini temel veri yapısı olarak kullanır.

Görüntü İşleme: NumPy dizileri, görüntüleri temsil etmek ve işlemek için kullanılabilir. OpenCV gibi görüntü işleme kütüphaneleri NumPy'yi temel bir bağımlılık olarak kullanır.

Finansal Modelleme: NumPy, finansal modellemede kullanılan karmaşık matematiksel hesaplamaları gerçekleştirmek için kullanılabilir.

### 2. Numpy ile 1D, 2D ve 3D array nasıl oluşturursunuz?

In [19]:
#1D array (Vektörler)
import numpy as np
# Liste kullanarak 1D dizi oluşturma
dizi_1d = np.array([1, 2, 3, 4, 5])

# Sıfırlardan oluşan 1D dizi oluşturma
sifirlar_1d = np.zeros(5)

# Birlerden oluşan 1D dizi oluşturma
birler_1d = np.ones(5)

# Belirli bir aralıkta değerler içeren 1D dizi oluşturma
aralik_1d = np.arange(1, 10, 2) 

In [20]:
print(dizi_1d)
print(sifirlar_1d)
print(birler_1d)
print(aralik_1d)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]


In [21]:
# 2D array (Matrisler)

# İçiçe liste kullanarak 2D dizi oluşturma
dizi_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Sıfırlardan oluşan 2D dizi oluşturma
sifirlar_2d = np.zeros((3, 4)) # 3 satır, 4 sütun

# Birlerden oluşan 2D dizi oluşturma
birler_2d = np.ones((2, 3)) # 2 satır, 3 sütun

# Rastgele sayılardan oluşan 2D dizi oluşturma
rastgele_2d = np.random.rand(2, 2)

print(dizi_2d)
print(sifirlar_2d)
print(birler_2d)
print(rastgele_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.20753618 0.361302  ]
 [0.27842973 0.69497607]]


In [22]:
# 3D array (Tensörler)

# İçiçe listeler kullanarak 3D dizi oluşturma
dizi_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Sıfırlardan oluşan 3D dizi oluşturma
sifirlar_3d = np.zeros((2, 3, 4)) # 2 derinlik, 3 satır, 4 sütun

# Birlerden oluşan 3D dizi oluşturma
birler_3d = np.ones((3, 2, 2)) # 3 derinlik, 2 satır, 2 sütun

print(dizi_3d)
print(sifirlar_3d)
print(birler_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


---

In [23]:
import numpy as np

arr1 = np.arange(0,2)
arr2 = np.arange(6,10).reshape(2,-1)
arr3 = np.array([[0,1],[1,0]])
arr1, arr2, arr3

(array([0, 1]),
 array([[6, 7],
        [8, 9]]),
 array([[0, 1],
        [1, 0]]))

### 3. arr1 ve arr2'yi nasıl toplarsınız?

In [24]:
arr1 + arr2

array([[ 6,  8],
       [ 8, 10]])

### 4. arr2 ve arr3 arraylerini horizontal ve vertical olarak nasıl birleştirirsiniz (concat)?

In [25]:
np.concatenate((arr2, arr3), axis=1)

array([[6, 7, 0, 1],
       [8, 9, 1, 0]])

In [26]:
np.concatenate((arr2, arr3), axis=0)

array([[6, 7],
       [8, 9],
       [0, 1],
       [1, 0]])

### 5. [4,1,5,7,0] dizesindeki en büyük iki elemanın indexini numpy ile nasıl gösterirsiniz?

In [27]:
np.argsort([4,1,5,7,0])[-2:] # küçükten büyüğe sıralayarak indexleri gösterir.

array([2, 3], dtype=int64)

### 6. Numpy'da np.mean() ve np.average() arasındaki fark nedir?


* np.mean() yöntemi aritmetik ortalamayı hesaplar ve girdi ve sonuçlar için ek seçenekler sunar. Örneğin, hangi veri türlerinin alınması gerektiğini, sonucun nereye yerleştirilmesi gerektiğini vb. belirtme seçeneğine sahiptir. 

* np.average() weights parametresi belirtilirse ağırlıklı ortalamayı hesaplar. Ağırlıklı ortalama durumunda, her veri noktasının nihai ortalamaya eşit şekilde katkıda bulunduğunu düşünmek yerine, bazı veri noktalarının diğerlerinden daha fazla ağırlığa sahip olduğunu (eşit olmayan katkı) düşünür.

In [28]:
#np.mean()
a = np.array([1, 2, 3, 4])
ortalama = np.mean(a)
print(ortalama)

2.5


In [29]:
#np.average()
a = np.array([1, 2, 3, 4])
agirliklar = np.array([4, 3, 2, 1])
agirlikli_ortalama = np.average(a, weights=agirliklar)
print(agirlikli_ortalama)

2.0


### 7. arr[:,0] ve arr[:,[0]] arasında ne fark var?

arr[:,0] tek boyutlu bir vektör döndürürken, arr[:,[0]] iki boyutlu bir matris döndürür.


In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[:,0]) # arr sütunundaki tüm satırların ilk elamanını getirdi.

[1 4 7]


In [31]:
print(arr[:,[0]]) # arr sütunundaki tüm satırların ilk elamanını getirdi. iki boyutlu olarak getirdi.

[[1]
 [4]
 [7]]


In [32]:
import pandas as pd

### 8. Bir pandas DataFrame'i Numpy array'e nasıl dönüştürürsünüz?

In [33]:
# Bir DataFrame oluşturun
data = {'isim': ['Ali', 'Veli', 'Ayşe'],
        'yaş': [25, 30, 28],
        'şehir': ['Ankara', 'İstanbul', 'İzmir']}
df = pd.DataFrame(data)

# DataFrame'i NumPy dizisine dönüştürün
dizi = df.to_numpy()

print("DataFrame:\n", df)
print("\nNumPy Dizisi:\n", dizi)

DataFrame:
    isim  yaş     şehir
0   Ali   25    Ankara
1  Veli   30  İstanbul
2  Ayşe   28     İzmir

NumPy Dizisi:
 [['Ali' 25 'Ankara']
 ['Veli' 30 'İstanbul']
 ['Ayşe' 28 'İzmir']]


### 9. Verilen bir NumPy arrayin bir dize öğesini büyük harfe, küçük harfe, ilk harfi büyük harfe, başlığı büyük harfe ve swapcase'e dönüştüren bir program yazın.?

In [34]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['Hello world', 'numpy is great', 'Python Programming'])

# Convert to different cases
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
capitalized_array = np.char.capitalize(string_array)
titlecase_array = np.char.title(string_array)
swapcase_array = np.char.swapcase(string_array)

# Print the results
print("Original Array:")
print(string_array)
print("\nUppercase:")
print(uppercase_array)
print("\nLowercase:")
print(lowercase_array)
print("\nCapitalized:")
print(capitalized_array)
print("\nTitle Case:")
print(titlecase_array)
print("\nSwap Case:")
print(swapcase_array)

Original Array:
['Hello world' 'numpy is great' 'Python Programming']

Uppercase:
['HELLO WORLD' 'NUMPY IS GREAT' 'PYTHON PROGRAMMING']

Lowercase:
['hello world' 'numpy is great' 'python programming']

Capitalized:
['Hello world' 'Numpy is great' 'Python programming']

Title Case:
['Hello World' 'Numpy Is Great' 'Python Programming']

Swap Case:
['hELLO WORLD' 'NUMPY IS GREAT' 'pYTHON pROGRAMMING']


---

## Pandas soruları

### 1. Pandas nedir ve ne amaçla kullanılır?

Pandas, Python programlama dilinde veri manipülasyonu ve analizi için kullanılan açık kaynak kodlu, hızlı, güçlü, esnek ve kullanımı kolay bir kütüphanedir. Temel olarak iki veri yapısı üzerine kuruludur:

Seriler (Series): Tek boyutlu, etiketlenmiş bir veri dizisidir.

Veri Çerçeveleri (DataFrames): İki boyutlu, etiketlenmiş bir veri tablosu olarak düşünülebilir.

Pandas kütüphanesi, veri bilimi ve makine öğrenmesi alanlarında yaygın olarak kullanılır ve aşağıdaki amaçlarla tercih edilir:

Veri Okuma ve Yazma: CSV, Excel, SQL veritabanları, JSON dosyaları gibi farklı formatlardaki verileri okuma ve bu formatlarda dosyalar yazma imkanı sağlar.

Veri Temizleme: Eksik verileri doldurma, verileri dönüştürme, hatalı verileri düzeltme gibi veri temizleme işlemlerini kolaylaştırır.

Veri Dönüştürme: Verileri yeniden şekillendirme, sütunları birleştirme veya ayırma, verileri gruplama gibi işlemleri gerçekleştirebilirsiniz.

Veri Analizi: Verileri filtreleme, sıralama, istatistiksel hesaplamalar yapma, grafikler oluşturma gibi veri analizi işlemlerini destekler.

Veri Görselleştirme: Matplotlib ve Seaborn gibi popüler görselleştirme kütüphaneleriyle entegre çalışarak verileri görsel olarak analiz etmeyi sağlar.

### 2. Verilen dataframede 25 - 30 yaş aralığındaki kişilere ait verileri yazdırın.

In [35]:
import pandas as pd

In [36]:
data = {
    "Name": ["John", "Emma", "Luke", "Emily", "Oliver"],
    "Age": [25, 28, 32, 21, 35],
    "Gender": ["Male","Female","Male","Female","Male"],
    "Salary": [50000, 60000, 70000, 55000, 80000]
}
df = pd.DataFrame(data)
df

Name  Age  Gender  Salary
0    John   25    Male   50000
1    Emma   28  Female   60000
2    Luke   32    Male   70000
3   Emily   21  Female   55000
4  Oliver   35    Male   80000

In [37]:
df.loc[(df["Age"]>=25) & (df["Age"]<=30)]

Name  Age  Gender  Salary
0  John   25    Male   50000
1  Emma   28  Female   60000

### 3. Her cinsiyet için maximum ve median maaşları yazdırınız.

In [38]:
df.groupby("Gender").aggregate(max_salary=("Salary", "max"),median_salary = ("Salary","median"))

max_salary  median_salary
Gender                           
Female       60000        57500.0
Male         80000        70000.0

### 4. Her birey için yaş ve maaşı kullanarak bonus hesaplayan bir fonksiyon uygulayın. Bonus 30 yaşın altındakiler için % 10, 30 yaş ve üzerindekiler için % 15 olmalı.

In [39]:
df["bonus"] = df[["Salary","Age"]].apply(lambda x: 0.1*x["Salary"] if x["Age"]<30 else 0.15*x["Salary"], axis=1)
df

Name  Age  Gender  Salary    bonus
0    John   25    Male   50000   5000.0
1    Emma   28  Female   60000   6000.0
2    Luke   32    Male   70000  10500.0
3   Emily   21  Female   55000   5500.0
4  Oliver   35    Male   80000  12000.0

### 5. Bir dataframede boş değerlerle (missing value) nasıl başa çıkarsınız?

In [40]:
df = pd.DataFrame({'A': [1, 2, None, 4],
                 'B': [5, None, 7, 8],
                 'C': [9, 10, 11, 12]})

df.isnull() 

A      B      C
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False  False

In [41]:
# Tespit etme
df.isna().sum()

A    1
B    1
C    0
dtype: int64

Silme (dropping)

In [42]:
# Boş değer içeren satırları sil
df.dropna()

# 'B' sütununda boş değer içeren satırları sil
df.dropna(subset=['B'])

# En az 3 adet null olmayan değere sahip satırları tut
df.dropna(thresh=3)

A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

Doldurma (Filling)

In [43]:
# Boş değerleri 0 ile doldur
df.fillna(0)

# 'A' sütunundaki boş değerleri sütunun ortalaması ile doldur
df['A'].fillna(df['A'].mean(), inplace=True)

# Her sütundaki boş değerleri o sütunun medyanı ile doldur
df.fillna(df.median())

# Önceki değerlerle doldur (ileri yönlü)
df.fillna(method='ffill')

# Sonraki değerlerle doldur (geri yönlü)
df.fillna(method='bfill')


A    B   C
0  1.000000  5.0   9
1  2.000000  7.0  10
2  2.333333  7.0  11
3  4.000000  8.0  12

İnterpolasyon (Interpolation)

interpolate() fonksiyonu: Boş değerleri komşu değerlerden tahmin etmek için farklı interpolasyon yöntemleri kullanılır.

In [44]:
# Lineer interpolasyon kullanarak boş değerleri doldur
df.interpolate(method='linear')

A    B   C
0  1.000000  5.0   9
1  2.000000  6.0  10
2  2.333333  7.0  11
3  4.000000  8.0  12

Hangi yöntemin en uygun olduğu, verilerin yapısına, boş değerlerin dağılımına ve analiz amacına bağlıdır.

Veri setiniz büyükse ve boş değerlerin oranı düşükse, silme yöntemi tercih edilebilir.
Boş değerlerin rastgele dağıldığı durumlarda, doldurma yöntemi daha uygun olabilir.
Zaman serisi verilerinde ise interpolasyon yöntemi daha iyi sonuçlar verebilir.

### 6. Pandas'da join ve merge nasıl kullanılır?

merge() fonksiyonu daha çok kompleks birleştirmeler için tercih edilir.

Merge Parametreleri:

left: Birleştirilecek sol DataFrame.

right: Birleştirilecek sağ DataFrame.

how: Birleştirme türünü belirtir. 'left', 'right', 'outer', 'inner' değerlerini alabilir. Varsayılan değer 'inner'dır.

-inner: Her iki DataFrame'de de ortak olan satırları döndürür.

-left: Sol DataFrame'deki tüm satırları ve sağ DataFrame'de eşleşen satırları döndürür.

-right: Sağ DataFrame'deki tüm satırları ve sol DataFrame'de eşleşen satırları döndürür.

-outer: Her iki DataFrame'deki tüm satırları döndürür.

on: Birleştirme işleminde kullanılacak sütun adını veya adlarını belirtir.

left_on: Sol DataFrame'de birleştirme işleminde kullanılacak sütun adını veya adlarını belirtir.

right_on: Sağ DataFrame'de birleştirme işleminde kullanılacak sütun adını veya adlarını belirtir.

left_index: Sol DataFrame'in indeksini birleştirme işleminde kullanmak için True olarak ayarlanır.

right_index: Sağ DataFrame'in indeksini birleştirme işleminde kullanmak için True olarak ayarlanır.

In [45]:
# DataFrame'leri oluşturalım
df1 = pd.DataFrame({'id': [1, 2, 3], 'isim': ['Ali', 'Veli', 'Ayşe']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'soyisim': ['Yılmaz', 'Kaya', 'Demir']})

# 'id' sütununa göre birleştirelim
merged_df = pd.merge(df1, df2, on='id')

print(merged_df)

   id  isim soyisim
0   2  Veli  Yılmaz
1   3  Ayşe    Kaya


Join Parametreleri:

right: Birleştirilecek sağ DataFrame.

how: Birleştirme türünü belirtir. 'left', 'right', 'outer', 'inner' değerlerini alabilir. Varsayılan değer 'left'tir.

on: Sol DataFrame'de birleştirme işleminde kullanılacak sütun adını veya adlarını belirtir. Varsayılan olarak, indeks kullanılır.

lsuffix: Sol DataFrame'deki çakışan sütun adlarına eklenecek soneki belirtir.

rsuffix: Sağ DataFrame'deki çakışan sütun adlarına eklenecek soneki belirtir.

In [46]:
# DataFrame'leri oluşturalım
df1 = pd.DataFrame({'isim': ['Ali', 'Veli', 'Ayşe']}, index=[1, 2, 3])
df2 = pd.DataFrame({'soyisim': ['Yılmaz', 'Kaya', 'Demir']}, index=[2, 3, 4])

# İndekslere göre birleştirelim
joined_df = df1.join(df2)

print(joined_df)

   isim soyisim
1   Ali     NaN
2  Veli  Yılmaz
3  Ayşe    Kaya


### 7. Bir dataframedeki bir sütunun tüm elemanlarına bir fonksiyonu nasıl uygularsınız?

In [47]:
# Örnek DataFrame
data = {'isim': ['Ali', 'Ayşe', 'Mehmet'],
        'yaş': [25, 30, 28]}
df = pd.DataFrame(data)

# Yaş sütunundaki her bir değere 2 ekleyen bir fonksiyon
def yasa_iki_ekle(yas):
  return yas + 2

# Fonksiyonu apply() metodu ile yaş sütununa uygulayalım
df['yeni_yaş'] = df['yaş'].apply(yasa_iki_ekle)

# Sonucu yazdıralım
print(df)

     isim  yaş  yeni_yaş
0     Ali   25        27
1    Ayşe   30        32
2  Mehmet   28        30


Lambda ile yapılışı

In [48]:
# Yaş sütunundaki her bir değeri 2 ile çarpma
df['iki_kat_yaş'] = df['yaş'].apply(lambda x: x * 2)

In [49]:
df

isim  yaş  yeni_yaş  iki_kat_yaş
0     Ali   25        27           50
1    Ayşe   30        32           60
2  Mehmet   28        30           56

### 8. Bir dataframedeki tekrarlı verileri nasıl ele alırsınız?

In [50]:

# Örnek bir DataFrame oluşturma
data = {
    'A': [1, 2, 2, 3, 4, 4],
    'B': ['a', 'b', 'b', 'c', 'd', 'd']
}
df = pd.DataFrame(data)

# Tekrarlı verileri tespit etme
duplicates = df.duplicated()
print("Tekrarlı Satırlar:")
print(duplicates)

Tekrarlı Satırlar:
0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool


In [51]:
df.duplicated().sum()

2

In [52]:
# Tekrarlı satırları inceleme
duplicate_rows = df[df.duplicated()]
print("\nTekrarlı Satırlar:")
print(duplicate_rows)


Tekrarlı Satırlar:
   A  B
2  2  b
5  4  d


In [53]:
# Tekrarlı satırları kaldırma
df_unique = df.drop_duplicates()
print("\nTekrarsız DataFrame:")
print(df_unique)


Tekrarsız DataFrame:
   A  B
0  1  a
1  2  b
3  3  c
4  4  d


In [54]:
# Sadece 'A' sütununa göre tekrarlı satırları kaldırma
df_unique_subset = df.drop_duplicates(subset=['A'])
print("\n'A' Sütununa Göre Tekrarsız DataFrame:")
print(df_unique_subset)


'A' Sütununa Göre Tekrarsız DataFrame:
   A  B
0  1  a
1  2  b
3  3  c
4  4  d


In [55]:
df.value_counts()

A  B
2  b    2
4  d    2
1  a    1
3  c    1
Name: count, dtype: int64

### 9. Pandasta kategorik veriyi numerik formata nasıl çevirirsiniz?

Genel olarak kullanılan iki yaklaşım Label Encoding ve One Hot Encoding.

**Label Encoding**

In [56]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Örnek bir DataFrame oluşturma
data = {
    'Renk': ['Kırmızı', 'Mavi', 'Yeşil', 'Kırmızı', 'Mavi', 'Sarı'],
    'Miktar': [10, 15, 10, 20, 25, 30]
}
df = pd.DataFrame(data)

print("Orijinal DataFrame:")
print(df)

Orijinal DataFrame:
      Renk  Miktar
0  Kırmızı      10
1     Mavi      15
2    Yeşil      10
3  Kırmızı      20
4     Mavi      25
5     Sarı      30


In [57]:

# LabelEncoder nesnesi oluşturma
label_encoder = LabelEncoder()

# 'Renk' sütununu sayısal verilere dönüştürme
df['Renk_encoded'] = label_encoder.fit_transform(df['Renk'])

print("\nLabel Encoding Uygulandıktan Sonra DataFrame:")
print(df)

# Kategorik değerlerin etiketlerini görüntüleme
print("\nKategorik Değerlerin Etiketleri:")
for i, item in enumerate(label_encoder.classes_):
    print(f"{item}: {i}")


Label Encoding Uygulandıktan Sonra DataFrame:
      Renk  Miktar  Renk_encoded
0  Kırmızı      10             0
1     Mavi      15             1
2    Yeşil      10             3
3  Kırmızı      20             0
4     Mavi      25             1
5     Sarı      30             2

Kategorik Değerlerin Etiketleri:
Kırmızı: 0
Mavi: 1
Sarı: 2
Yeşil: 3


**One Hot Encoding**

In [58]:
# Örnek bir DataFrame oluşturma
data = {
    'Renk': ['Kırmızı', 'Mavi', 'Yeşil', 'Kırmızı', 'Mavi', 'Sarı'],
    'Miktar': [10, 15, 10, 20, 25, 30]
}
df = pd.DataFrame(data)

print("Orijinal DataFrame:")
print(df)

# One Hot Encoding uygulama
df_one_hot = pd.get_dummies(df, columns=['Renk'], drop_first=True)

print("\nOne Hot Encoding Uygulandıktan Sonra DataFrame:\n")
print(df_one_hot)

Orijinal DataFrame:
      Renk  Miktar
0  Kırmızı      10
1     Mavi      15
2    Yeşil      10
3  Kırmızı      20
4     Mavi      25
5     Sarı      30

One Hot Encoding Uygulandıktan Sonra DataFrame:

   Miktar  Renk_Mavi  Renk_Sarı  Renk_Yeşil
0      10      False      False       False
1      15       True      False       False
2      10      False      False        True
3      20      False      False       False
4      25       True      False       False
5      30      False       True       False


### 10. where() metodunu kullanarak sütunlara koşullu mantığın nasıl uygulanacağını gösterin.?

In [59]:
import pandas as pd

data = {'Ürün': ['A', 'B', 'C', 'D', 'E'],
        'Fiyat': [10, 25, 15, 30, 20],
        'Stok': [50, 30, 20, 10, 40]}

df = pd.DataFrame(data)
df

Ürün  Fiyat  Stok
0    A     10    50
1    B     25    30
2    C     15    20
3    D     30    10
4    E     20    40

In [60]:
# Fiyatı 20'den büyük olan ürünleri filtreleme
df.where(df['Fiyat'] > 20)

Ürün  Fiyat  Stok
0  NaN    NaN   NaN
1    B   25.0  30.0
2  NaN    NaN   NaN
3    D   30.0  10.0
4  NaN    NaN   NaN

In [61]:
# Stoku 25'ten az olan ürünlerin fiyatını 0 yapma
df['Fiyat'] = df['Fiyat'].where(df['Stok'] >= 25, other=0)
df

Ürün  Fiyat  Stok
0    A     10    50
1    B     25    30
2    C      0    20
3    D      0    10
4    E     20    40

In [62]:
# Birden fazla koşul kullanma
df.where((df['Fiyat'] > 15) & (df['Stok'] > 20), other='Düşük Stok')

Ürün       Fiyat        Stok
0  Düşük Stok  Düşük Stok  Düşük Stok
1           B          25          30
2  Düşük Stok  Düşük Stok  Düşük Stok
3  Düşük Stok  Düşük Stok  Düşük Stok
4           E          20          40

### 11. Bir DataFrame'deki verileri nasıl pivotlayabilirsiniz?

Pandas kütüphanesinde DataFrame'lerdeki verileri pivotlamak için pivot() ve pivot_table() fonksiyonları kullanılabilir. 

pivot() fonksiyon, verilerinizi yeniden şekillendirmenize ve belirli bir sütunu indeks, başka bir sütunu sütun başlıkları ve üçüncü bir sütunu da değerler olarak kullanarak yeni bir DataFrame oluşturmanıza olanak tanır.

In [63]:
# Örnek DataFrame
data = {'Tarih': ['2023-03-01', '2023-03-01', '2023-03-02', '2023-03-02'],
        'Ürün': ['A', 'B', 'A', 'B'],
        'Satış': [10, 15, 12, 20]}
df = pd.DataFrame(data)

df

Tarih Ürün  Satış
0  2023-03-01    A     10
1  2023-03-01    B     15
2  2023-03-02    A     12
3  2023-03-02    B     20

In [64]:
# DataFrame'i pivotlama
pivot_df = df.pivot(index='Tarih', columns='Ürün', values='Satış')

print(pivot_df)

Ürün         A   B
Tarih             
2023-03-01  10  15
2023-03-02  12  20


pivot_table() fonksiyonu aynı indeks ve sütun kombinasyonuna sahip birden fazla değeri işlemenize olanak tanır. Bunu yaparken, belirli bir agregasyon fonksiyonunu (varsayılan olarak mean) kullanarak bu değerleri birleştirir.

In [65]:
# Sample DataFrame with duplicate entries
data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-01'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles', 'New York'],
    'Temperature': [30, 70, 32, 68, 28]
}
df = pd.DataFrame(data)

print("Original DataFrame with Duplicates:")
print(df)

# Pivoting the DataFrame with aggregation
pivot_table_df = df.pivot_table(index='Date', columns='City', values='Temperature', aggfunc='mean')

print("\nPivot Table DataFrame:")
print(pivot_table_df)

Original DataFrame with Duplicates:
         Date         City  Temperature
0  2023-01-01     New York           30
1  2023-01-01  Los Angeles           70
2  2023-01-02     New York           32
3  2023-01-02  Los Angeles           68
4  2023-01-01     New York           28

Pivot Table DataFrame:
City        Los Angeles  New York
Date                             
2023-01-01           70        29
2023-01-02           68        32


### 12. Pandas ile bir dataframe'i csv olarak nasıl kaydedersiniz?

In [66]:
import pandas as pd

# Örnek bir DataFrame oluşturalım
data = {'İsim': ['Ali', 'Ayşe', 'Mehmet'],
        'Yaş': [25, 30, 28],
        'Şehir': ['İstanbul', 'Ankara', 'İzmir']}

df = pd.DataFrame(data)

# DataFrame'i "veri.csv" adlı bir CSV dosyasına kaydedelim
df.to_csv('veri.csv', index=False) 

### 13. Pandas'da slicing ve filtering nedir?

In [67]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Slicing the DataFrame to get the first three rows and the first two columns
sliced_df = df.iloc[0:3, 0:2]

print("\nSliced DataFrame (first 3 rows and first 2 columns):")
print(sliced_df)

Original DataFrame:
   A  B   C
0  1  a  10
1  2  b  20
2  3  c  30
3  4  d  40
4  5  e  50

Sliced DataFrame (first 3 rows and first 2 columns):
   A  B
0  1  a
1  2  b
2  3  c


In [68]:
# Filtering the DataFrame to get rows where column 'A' is greater than 2
filtered_df = df[df['A'] > 2]

print("\nFiltered DataFrame (rows where A > 2):")
print(filtered_df)


Filtered DataFrame (rows where A > 2):
   A  B   C
2  3  c  30
3  4  d  40
4  5  e  50
